export const BLOG_PROSE_CLASSES = [
  "prose",
  "prose-gray",
  "max-w-none",
  "prose-h1:text-3xl",
  "prose-h2:text-2xl",
  "prose-h3:text-xl",
  "prose-h4:text-lg",
  "prose-headings:text-gray-900",
  "prose-p:text-gray-700",
  "prose-a:text-blue-600",
  "prose-strong:text-gray-900",
  "prose-ul:list-disc",
  "prose-ol:list-decimal",
  "prose-headings:mt-10",
  "prose-headings:mb-4",
  "prose-p:my-5",
  "prose-p:leading-8",
  "prose-li:my-2",
  "prose-ul:my-6",
  "prose-ol:my-6",
  "prose-blockquote:my-8",
  "prose-pre:my-8",
  "dark:prose-invert",
].join(" ")